### ISSUE TITLE
path.isAbsolute is not a function

### ISSUE THREAD

**Issue by mecirmartin** [dsherret/ts-morph#955]
Hey, it's me, once again

I get this error when using ts-morph@10.0.1 in browser. Reverting to 9.0.1 fixes the bug

Maybe similar with #945 

Version: 10.0.1

<img width="1044" alt="Screenshot 2021-03-22 at 09 28 02" src="https://user-images.githubusercontent.com/55835379/111968665-b26e6080-8af9-11eb-845c-85a9df159902.png">

**Comment by dsherret** [comment]
@mecirmartin this might be fixed in 10.0.2 (just published), but I am not sure. I haven't been testing for a web version of ts-morph. I believe some build tools should be polyfilling node's `path` module, but maybe that's broken now because it is using `require("path")` instead of an ES module import now.

**Comment by mecirmartin** [comment]
Thank you for info, we are perfectly satisfied with 9.0.1, just wanted to let you know about this bug in 10.0.1

**Comment by mecirmartin** [comment]
I'm trying to use ts-morph with Vite and same problem occurs when running in browser. Ts-morph@9.1.0 is not working with Vite too. 
Found this in Vite issues https://github.com/vitejs/vite/issues/2618#issuecomment-804390679

Is there any way to get rid of node path module in ts-morph to enable this project to be used with modern build tools like Vite?

**Comment by dsherret** [comment]
@mecirmartin does it work with 10.0.2? I think using the path module is constrained to this file now https://github.com/dsherret/ts-morph/blob/latest/packages/common/src/runtimes/NodeRuntime.ts so it should not be difficult.

**Comment by mecirmartin** [comment]
It doesn't work with 10.0.2. Yeah I've went through the repo and found out that path module is being used only in this one file. I replaced it with path-browserify and everything works, all test pass

Just curious, why don't you add this one dependency. Wouldn't this make ts-morph more modular?

**Comment by dsherret** [comment]
@mecirmartin thanks for the suggestion! It was because I did not know about it. I've added it now.
